server:
  port: 5004

spring:
  application:
    name: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.22.108.106:5432/devpulse?serverTimezon=Asia/Seoul
    username: postgres
    password: devpulse

  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    # JPA 가 엔티티 클래스 기반으로 DDL(Data Definition Language)을 생성하도록 설정
    generate-ddl: true
    properties:
      hibernate:
        # Hibernate 가 실행하는 SQL 쿼리를 보기 좋게 포맷팅하여 출력
        format_sql: true
        # Hibernate 가 생성하는 SQL 쿼리에 주석 추가
        use_sql_comments: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 2

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
