server:
  port: 8762

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://127.0.0.1:5050'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: datacollection
          uri: lb://datacollection
          predicates:
            - Path=/datacollection/**
        - id: search
          uri: lb://search
          predicates:
            - Path=/search/**
        - id: recommendation
          uri: lb://recommendation
          predicates:
            - Path=/recommendation/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
        - id: content
          uri: lb://content
          predicates:
            - Path=/content/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG